include(":app")

// Capacitor's template creates this module even when it currently has no
// Cordova plugins. Keep it wired so a later sync cannot change the graph.
include(":capacitor-cordova-android-plugins")
project(":capacitor-cordova-android-plugins").projectDir =
    file("./capacitor-cordova-android-plugins/")

// Generated by `cap sync`; deliberately remains Groovy.
apply(from = "capacitor.settings.gradle")
